begin;
insert into compass_private.metric_definitions(id,name,department,tracking_area,unit) values
('real-estate-development-1','Projects on track / total','Real Estate Development',null,null),
('real-estate-development-2','Units under site control','Real Estate Development',null,null),
('real-estate-development-3','LIHTC applications submitted','Real Estate Development',null,null),
('real-estate-development-4','Units in pipeline','Real Estate Development',null,null),
('real-estate-development-5','New units created with CO','Real Estate Development',null,null),
('real-estate-development-6','Rehab units with CO','Real Estate Development',null,null),
('real-estate-development-7','Units closed','Real Estate Development',null,null),
('real-estate-development-8','Developer fee','Real Estate Development',null,null),
('real-estate-development-9','Average percent of development fee for closed projects','Real Estate Development',null,null),
('property-management-1','Noncompliance','Property Management',null,null),
('property-management-2','Rent collection','Property Management',null,null),
('property-management-3','Vacancy','Property Management',null,null),
('property-management-4','Resident satisfaction','Property Management',null,null),
('property-management-5','PM fee','Property Management',null,null),
('property-management-6','Positive move-outs','Property Management',null,null),
('property-management-7','Nonrenewals','Property Management',null,null),
('property-management-8','NPSIRE score (average)','Property Management',null,null),
('property-management-9','Unresolved resident complaints','Property Management',null,null),
('property-management-10','Curb appeal rating','Property Management',null,null),
('property-management-11','Troubled properties','Property Management',null,null),
('property-management-12','Average turnover time','Property Management',null,null),
('property-management-13','Average controllable cost','Property Management',null,null),
('property-management-14','Capital expenditure projects on track / total','Property Management',null,null),
('property-management-15','Average re-rental time','Property Management',null,null),
('property-management-16','Google Reviews (target 4.75)','Property Management',null,null),
('property-management-17','Resident survey response rate','Property Management',null,null),
('human-resources-1','Employee satisfaction','Human Resources',null,null),
('human-resources-2','Employee retention','Human Resources',null,null),
('human-resources-3','Employee engagement','Human Resources',null,null),
('human-resources-4','Open positions','Human Resources',null,null),
('human-resources-5','Actively recruiting','Human Resources',null,null),
('human-resources-6','Waiting to start','Human Resources',null,null),
('human-resources-7','Training satisfaction score','Human Resources',null,null),
('human-resources-8','Voluntary vs. involuntary exits and top three departure reasons','Human Resources',null,null),
('human-resources-9','Total employees','Human Resources',null,null),
('human-resources-10','Time to fill open positions','Human Resources',null,null),
('human-resources-11','LDP / total','Human Resources',null,null),
('human-resources-12','Employee net promoter score','Human Resources',null,null),
('human-resources-13','Employees receiving incentive program (%)','Human Resources',null,null),
('resident-services-1','Resident satisfaction','Resident Services',null,null),
('resident-services-2','Resident Experience Score','Resident Services',null,null),
('resident-services-3','Housing stability rate','Resident Services',null,null),
('resident-services-4','Resident services utilization rate','Resident Services',null,null),
('resident-services-5','Evictions prevented','Resident Services',null,null),
('resident-services-6','Resident engagement rate','Resident Services',null,null),
('resident-services-7','Service delivery connection rate','Resident Services',null,null),
('resident-services-8','Benefits leveraged for residents ($)','Resident Services',null,null),
('resident-services-9','Resident survey response rate','Resident Services',null,null),
('resident-services-10','Food distribution events','Resident Services',null,null),
('resident-services-11','Residents accessing food programs (%)','Resident Services',null,null),
('resident-services-12','Service delivery partners','Resident Services',null,null),
('resident-services-13','Positive move-outs becoming homeowners','Resident Services',null,null),
('community-relations-1','Contributed revenue total','Community Relations',null,null),
('community-relations-2','Contributed revenue: grants','Community Relations',null,null),
('community-relations-3','Contributed revenue: NeighborWorks','Community Relations',null,null),
('community-relations-4','Contributed revenue: individual giving','Community Relations',null,null),
('community-relations-5','Contributed revenue: corporate sponsors','Community Relations',null,null),
('community-relations-6','Corporate sponsor retention rate','Community Relations',null,null),
('community-relations-7','Giving increase from renewing corporate sponsors','Community Relations',null,null),
('community-relations-8','Predevelopment capital raised','Community Relations',null,null),
('community-relations-9','Grant success rate','Community Relations',null,null),
('community-relations-10','Grant yield rate','Community Relations',null,null),
('community-relations-11','Board giving','Community Relations',null,null),
('community-relations-12','Donor retention rate','Community Relations',null,null),
('community-relations-13','Brand visibility','Community Relations',null,null),
('community-relations-14','LinkedIn followers','Community Relations',null,null),
('community-relations-15','Social media engagement rate','Community Relations',null,null),
('community-relations-16','Facebook impressions','Community Relations',null,null),
('community-relations-17','Earned media coverage','Community Relations',null,null),
('community-relations-18','Subject matter expertise','Community Relations',null,null),
('finance-1','Days cash','Finance',null,null),
('finance-2','Total diverse spend (%)','Finance',null,null),
('finance-3','Accounts receivable','Finance',null,null),
('finance-4','Current ratio','Finance',null,null),
('finance-5','Excess cash to parent','Finance',null,null),
('finance-6','Payment of deferred developer fee','Finance',null,null),
('finance-7','Vacancy loss ($)','Finance',null,null),
('finance-8','Invoices paid within 30 days (%)','Finance',null,null),
('finance-9','Average controllable cost','Finance',null,null),
('finance-10','Properties meeting budgeted NOI','Finance',null,null),
('finance-11','Economic occupancy rate','Finance',null,null),
('finance-12','Monthly department financials by the 10th','Finance',null,null),
('finance-13','Properties closed by the 15th (%)','Finance',null,null),
('operations-1','Cybersecurity risk score',null,'Operations',null),
('operations-2','Technologies adopted',null,'Operations',null),
('operations-3','Technology user engagement',null,'Operations',null),
('operations-4','SOP revisions',null,'Operations',null),
('operations-5','Project plans completed on time (%)',null,'Operations',null),
('operations-6','Project plans submitted on time (%)',null,'Operations',null),
('operations-7','Projects on track (%)',null,'Operations',null),
('asset-management-fees','Asset management fees',null,'Management fees','USD')
on conflict(id) do update set name=excluded.name,department=excluded.department,tracking_area=excluded.tracking_area,unit=excluded.unit;
insert into compass_private.contribution_categories(id,label) values ('grant','Grant'),('neighborworks','NeighborWorks'),('individual','Individual gift'),('corporate','Corporate contribution'),('other','Other contribution') on conflict(id) do update set label=excluded.label;
insert into compass_private.releases(version) values('20260916_metric_catalog') on conflict do nothing;
commit;
