begin;
do $$ declare item jsonb; existing compass_private.properties; begin
 for item in select value from jsonb_array_elements('[{"name":"1528 West Apts","code":"1528","street":"1528 W Hamilton St","city":"Allentown","state":"PA","postalCode":"18102","population":"Senior 55+ Elderly & Handicapped","units":null},{"name":"Beach Run","code":"BEACH","street":"325 N. Center St.","city":"Fredericksburg","state":"PA","postalCode":"17026","population":"General","units":null},{"name":"Brandywine Ctr","code":"BHH","street":"744 E. Lincoln Hwy","city":"Coatesville","state":"PA","postalCode":"19320","population":"Senior 62+","units":null},{"name":"Claymont Street Apartments","code":"CLAY","street":"1300 E. 16th St.","city":"Wilmington","state":"DE","postalCode":"19805","population":"General / Section 8","units":null},{"name":"College Avenue Apartments","code":"COL","street":"213 College Ave","city":"Lancaster","state":"PA","postalCode":"17603","population":null,"units":null},{"name":"Duke Manor Apts.","code":"DMA","street":"716 Rockland St.","city":"Lancaster","state":"PA","postalCode":"17602","population":"Family HUD/Section 8","units":null},{"name":"Exeter Apartments (Bond 5 LP)","code":"XTR","street":"222 Schooley Ave.","city":"Exeter","state":"PA","postalCode":"18643","population":"Senior Tax Credit","units":null},{"name":"The Flats Phase I","code":"FLATS","street":"525 N Union St","city":"Wilmington","state":"DE","postalCode":"19805","population":"General / Section 8","units":null},{"name":"The Flats Phase II","code":"FLATS2","street":"601 N Union St","city":"Wilmington","state":"DE","postalCode":"19805","population":"General / Section 8","units":null},{"name":"The Flats Phase III","code":"FLATS3","street":"610 Bayard Ave","city":"Wilmington","state":"DE","postalCode":"19805","population":"General / Section 8","units":null},{"name":"The Flats Phase IV","code":"FLATS4","street":"610 Ferris St","city":"Wilmington","state":"DE","postalCode":"19805","population":"General / Section 8","units":null},{"name":"Glenbrook Apartments","code":"GLEN","street":"463 Main St","city":"Atglen","state":"PA","postalCode":"19310","population":"General","units":null},{"name":"Governors Gate Apartments","code":"GOVGATE","street":"405 Governors Park Drive","city":"Bellefonte","state":"PA","postalCode":"16823","population":"Family Section 8","units":null},{"name":"Hamburg School Apartments","code":"HAMBURG","street":"690 E State Street","city":"Hamburg","state":"PA","postalCode":"19526","population":"General / Section 8","units":null},{"name":"Henner Apts.","code":"HAA","street":"24 E. High St.","city":"Wolmelsdorf","state":"PA","postalCode":"19567","population":"Senior 55+ / Elderly & Handicapped","units":null},{"name":"Heritage Point Apartments","code":"HPA","street":"94 McGarraher Street","city":"Wilkes-Barre","state":"PA","postalCode":"18702","population":"General / Section 8","units":null}]'::jsonb) loop
  select * into existing from compass_private.properties where code=item->>'code';
  if found then continue; end if;
  select * into existing from compass_private.properties where name=item->>'name';
  if found then
   if existing.code is not null then raise exception 'Property name already has another code: %',existing.name; end if;
   update compass_private.properties set code=item->>'code',street=coalesce(street,item->>'street'),city=coalesce(city,item->>'city'),state=coalesce(state,item->>'state'),postal_code=coalesce(postal_code,item->>'postalCode'),population=coalesce(population,item->>'population'),revision=revision+1 where id=existing.id;
  else
   insert into compass_private.properties(name,code,street,city,state,postal_code,population,location)
   values(item->>'name',item->>'code',item->>'street',item->>'city',item->>'state',item->>'postalCode',item->>'population',concat_ws(', ',item->>'street',item->>'city',concat_ws(' ',item->>'state',item->>'postalCode')));
  end if;
 end loop;
end $$;
commit;
