import {featureCatalog} from '../../data/featureCatalog.js';
import {mountPositions,mountMetricGovernance} from './positions.js';
import {mountArchive} from './archive.js';

const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roles=['admin','executive','elt','director','staff','external'];
const roleName=r=>({admin:'System Admin',executive:'Executive',elt:'ELT',director:'OLT Director',staff:'Department Staff',external:'Board / External'})[r];
const activeFeatures=[['strategic','2030 Plan Scorecard'],['annual','Annual Scorecard'],['metrics','Record progress'],['weekly','Weekly Accountability'],['learn','Learn']].map(([key,label])=>({key,label,category:'Current navigation'}));
const features=[...activeFeatures,...featureCatalog.filter(f=>!activeFeatures.some(a=>a.key===f.key))];
const checks=(name,items,selected=[])=>items.map(([value,label])=>`<label class="check"><input type="checkbox" name="${name}" value="${esc(value)}" ${selected.includes(value)?'checked':''}>${esc(label)}</label>`).join('');
const options=(items,value='')=>`<option value="">Unassigned</option>${items.map(m=>`<option value="${m.userId}" ${m.userId===value?'selected':''}>${esc(m.positionTitle||m.email)}</option>`).join('')}`;
let navigationGuard=null;
const caption=m=>`${m.positionTitle||'Needs assignment'} · ${m.email}`;
function download(rows,name){
 const headers=[...new Set(rows.flatMap(r=>Object.keys(r)))];
 const cell=v=>{let text=typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'');if(/^[\s]*[=+@-]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};
 const csv=[headers,...rows.map(r=>headers.map(k=>r[k]))].map(r=>r.map(cell).join(',')).join('\r\n');
 const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);
}
export async function mountCommandCenter(root,store,roster){
 const workspace=await store.adminWorkspace();if(!root.querySelector('#admin-user'))return;
 let selected='users',dirty=false,busy=false;
 const hero=root.querySelector('.hero');hero.querySelector('h2').textContent='Admin command center';hero.querySelector('p').textContent='People, access and operating records.';
 const users=document.createElement('section');users.id='admin-panel-users';
 for(const child of [...root.children])if(child!==hero)users.append(child);
 root.append(users);
 const targets=users.querySelector('#target-form').closest('details');targets.open=true;
 const tabs=[['users','Users'],['positions','Positions'],['governance','Metric governance'],['teams','Teams'],['permissions','Permissions'],['features','Feature rollout'],['properties','Property governance'],['records','Data table'],['targets','Targets'],['history','History']];
 const nav=document.createElement('nav');nav.className='tabs admin-tabs';nav.setAttribute('aria-label','Admin sections');nav.innerHTML=tabs.map(([id,label])=>`<button class="tab" type="button" data-admin-tab="${id}" aria-pressed="${id==='users'}">${label}</button>`).join('');hero.after(nav);
 const panels={users};for(const [id] of tabs.filter(([id])=>id!=='users')){const panel=document.createElement('section');panel.id='admin-panel-'+id;panel.hidden=true;root.append(panel);panels[id]=panel;}panels.targets.append(targets);
 const banner=document.createElement('p');banner.className='admin-stats';banner.textContent=`${roster.members.length} accounts · ${roster.members.filter(m=>m.active).length} active · ${roster.departments.length} departments`;users.prepend(banner);
 const search=document.createElement('label');search.className='field';search.innerHTML='Find an account<input id="admin-search" type="search" placeholder="Email, position or department">';banner.after(search);
 search.querySelector('input').oninput=e=>{const q=e.target.value.toLowerCase();for(const option of users.querySelector('#admin-user').options){const m=roster.members.find(m=>m.userId===option.value);option.hidden=!!m&&!`${caption(m)} ${m.departments.join(' ')}`.toLowerCase().includes(q);}};
 const newUser=document.createElement('details');newUser.className='card learn-card';newUser.innerHTML=`<summary>Connect a person</summary><form class="entry-form" id="create-user-form"><p>Create and configure positions in Positions first. Add a work email when you are ready to connect a person.</p><label>Work email<input name="email" type="email" autocomplete="off" maxlength="254" required></label><fieldset><legend>Assigned positions</legend><div id="connect-positions"></div></fieldset><p>The person will sign in with Microsoft. No email is sent by this action.</p><button type="submit" class="primary-button">Connect person</button><p role="status" id="create-user-result"></p></form>`;search.after(newUser);
 const refreshPositionChoices=()=>{newUser.querySelector('#connect-positions').innerHTML=roster.positions.length?checks('positionIds',roster.positions.map(p=>[p.id,p.title])):'Create a position before connecting a person.';};refreshPositionChoices();
 let attempt=null;
 newUser.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,f=new FormData(form),result=form.querySelector('[role="status"]');const payload={action:'create',email:f.get('email'),positionIds:f.getAll('positionIds')};
   if(!payload.positionIds.length){result.textContent='Select at least one position.';return;}
   const signature=JSON.stringify(payload);if(!attempt||attempt.signature!==signature)attempt={signature,id:crypto.randomUUID()};payload.requestId=attempt.id;
   busy=true;for(const field of form.elements)field.disabled=true;result.textContent='Creating account…';
   try{const saved=await store.manageUser(payload);const updated=await store.members();roster.members.splice(0,roster.members.length,...updated.members);roster.positions=updated.positions;
     const select=users.querySelector('#admin-user');select.innerHTML='<option value="">Choose an account</option>'+roster.members.map(m=>`<option value="${m.userId}">${esc(caption(m))}</option>`).join('');select.value=saved.userId;select.dispatchEvent(new Event('change'));result.textContent=saved.message;dirty=false;attempt=null;
     banner.textContent=`${roster.members.length} accounts · ${roster.members.filter(m=>m.active).length} active · ${roster.departments.length} departments`;
   }catch(error){result.textContent=error.message;}finally{busy=false;for(const field of form.elements)field.disabled=false;}
 };
 const invitation=document.createElement('div');users.append(invitation);
 const showInvite=()=>{const member=roster.members.find(m=>m.userId===users.querySelector('#admin-user').value);invitation.innerHTML=member?`<div class="card learn-card"><p>${member.confirmed?'Email verified.':'Email verification pending.'}</p>${member.confirmed?'':'<button type="button" class="quiet-button" id="send-invitation">Send invitation</button>'}<p role="status"></p></div>`:'';
  invitation.querySelector('button')?.addEventListener('click',async e=>{e.target.disabled=true;const message=invitation.querySelector('[role="status"]');message.textContent='Sending invitation…';try{const response=await store.manageUser({action:'invite',email:member.email});message.textContent=response.message;}catch(error){message.textContent=error.message;}finally{e.target.disabled=false;}});
 };users.querySelector('#admin-user').addEventListener('change',showInvite);
 const workspaceTest=document.createElement('section');workspaceTest.className='card learn-card';workspaceTest.hidden=true;users.append(workspaceTest);
 const selectedAccount=users.querySelector('#admin-user');
 const showWorkspaceTest=()=>{
  const member=roster.members.find(m=>m.userId===selectedAccount.value);
  workspaceTest.hidden=!member;if(!member)return;
  workspaceTest.innerHTML=`<h3>Open this person’s workspace</h3><p>Test their current permissions and navigation without their Microsoft account. Your Admin sign-in stays active. Access lasts up to one hour.</p><label class="check"><input type="checkbox" id="workspace-allow-writes">Allow saving as this user</label><p>When enabled, saves change real records and are logged under your Admin identity as well.</p><button type="button" class="primary-button" id="open-workspace" ${member.active?'':'disabled'}>View as user</button><p role="status">${member.active?'':'Activate this account before opening its workspace.'}</p>`;
  workspaceTest.querySelector('button').onclick=async e=>{
   if(!guard())return;e.target.disabled=true;const result=workspaceTest.querySelector('[role="status"]');result.textContent='Opening workspace…';
   try{await store.startWorkspace(member.userId,workspaceTest.querySelector('input').checked);dirty=false;}
   catch(error){result.textContent=error.message;e.target.disabled=false;}
  };
 };selectedAccount.addEventListener('change',showWorkspaceTest);
 const refresh=async()=>Object.assign(workspace,await store.adminWorkspace());
 const guard=()=>!busy&&(!dirty||confirm('Discard unsaved Admin changes?'));
 root.addEventListener('compass-admin-saved',()=>{dirty=false;});
 if(navigationGuard)document.removeEventListener('click',navigationGuard,true);
 navigationGuard=e=>{if(!root.querySelector('.admin-tabs'))return;const link=e.target.closest('[data-surface]');if(link&&link.dataset.surface!=='admin'&&!guard()){e.preventDefault();e.stopImmediatePropagation();}};
 document.addEventListener('click',navigationGuard,true);
 root.addEventListener('input',e=>{if(e.target.closest('form:not(#record-filter)'))dirty=true;});
 root.addEventListener('change',e=>{if(e.target.closest('form:not(#record-filter)'))dirty=true;});
 nav.onclick=async e=>{const tab=e.target.closest('[data-admin-tab]');if(!tab||!guard())return;selected=tab.dataset.adminTab;dirty=false;for(const [key,panel] of Object.entries(panels))panel.hidden=key!==selected;for(const button of nav.querySelectorAll('button'))button.setAttribute('aria-pressed',String(button===tab));try{await renderPanel();}catch(error){panels[selected].innerHTML=`<p role="alert">${esc(error.message)}</p>`;}};
 function bindSave(panel,save,after){panel.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,result=form.querySelector('[role="status"]');busy=true;for(const b of form.querySelectorAll('button'))b.disabled=true;result.textContent='Saving…';try{await save(new FormData(form));await refresh();dirty=false;await after();}catch(error){result.textContent=error.message;}finally{busy=false;for(const b of form.querySelectorAll('button'))b.disabled=false;}};}
 function teams(){const panel=panels.teams;panel.innerHTML=`<h3>Teams</h3><p>Assign people to shared working groups across departments.</p><div class="admin-grid">${workspace.teams.map(t=>`<button class="linked" data-team="${t.id}"><strong>${esc(t.name)}</strong><span>${t.members.length} members · ${t.active?'Active':'Archived'}</span></button>`).join('')}</div><button class="quiet-button" data-new-team>Create team</button><div id="team-editor"></div>`;
  const edit=t=>{const editor=panel.querySelector('#team-editor');editor.innerHTML=`<form class="entry-form"><label>Team name<input name="name" required maxlength="120" value="${esc(t?.name)}"></label><label>Description<textarea name="description" maxlength="2000">${esc(t?.description)}</textarea></label><label class="check"><input type="checkbox" name="active" ${t?.active!==false?'checked':''}>Active team</label><fieldset><legend>Members</legend>${checks('members',roster.members.filter(m=>m.active).map(m=>[m.userId,caption(m)]),t?.members||[])}</fieldset><button class="primary-button">Save team</button><p role="status"></p></form>`;bindSave(editor,f=>store.saveTeam({id:t?.id,name:f.get('name'),description:f.get('description'),active:f.has('active'),members:f.getAll('members'),expectedRevision:t?.revision??null}),teams);};
  panel.querySelector('[data-new-team]').onclick=()=>{if(guard())edit(null);};panel.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>{if(guard())edit(workspace.teams.find(t=>t.id===b.dataset.team));});
 }
 function permissions(){panels.permissions.innerHTML=`<h3>Permissions</h3><p>Permissions control data access. Feature rollout controls what appears in navigation.</p><div class="admin-grid">${roles.map(role=>`<article class="card learn-card"><h3>${roleName(role)}</h3><p>${({admin:'Manages users, settings and all Admin controls.',executive:'Reads metrics, drafts and weekly accountability; submits for assigned positions.',elt:'Uses metric assignments and weekly permissions from the working position.',director:'Records assigned measures and submits for the working position.',staff:'Metric access follows position assignments; no weekly submissions by default.',external:'Access follows position settings; no weekly submissions by default.'})[role]}</p><p>${roster.members.filter(m=>(m.effectiveRoles||m.roles).includes(role)).length} assigned accounts</p></article>`).join('')}</div><h3>Account overrides</h3><div class="admin-table-wrap"><table><thead><tr><th>Position</th><th>Roles</th><th>Metric read / write</th><th>Weekly read / write</th><th>Active</th></tr></thead><tbody>${roster.members.map(m=>`<tr><th>${esc(m.positionTitle||m.email)}</th><td>${(m.effectiveRoles||m.roles).map(roleName).join(', ')}</td><td>${[m.readMetrics,m.writeMetrics].map(v=>v===false?'Deny':'Follow position').join(' / ')}</td><td>${[m.readWeekly,m.writeWeekly].map(v=>v===false?'Deny':'Follow position').join(' / ')}</td><td>${m.active?'Yes':'No'}</td></tr>`).join('')}</tbody></table></div>`;}
 function rollout(){const panel=panels.features;panel.innerHTML=`<h3>Feature rollout</h3><p>Choose what each person sees. Manage data permissions in Users.</p><label class="field">Account<select id="feature-user">${roster.members.filter(m=>m.roles.length||m.positions.length).map(m=>`<option value="${m.userId}">${esc(caption(m))}</option>`).join('')}</select></label><button class="quiet-button" id="reset-features">Reset to position defaults</button><p role="status" id="feature-result"></p><div id="feature-switches"></div>`;
  const userSelect=panel.querySelector('select');const draw=()=>{const member=roster.members.find(m=>m.userId===userSelect.value);panel.querySelector('#feature-switches').innerHTML=member?[...new Set(features.map(f=>f.category))].map(category=>`<fieldset class="feature-group"><legend>${esc(category)}</legend>${features.filter(f=>f.category===category).map(f=>{const override=workspace.features.find(o=>o.userId===member.userId&&o.key===f.key);return `<label class="feature-control"><span><strong>${esc(f.label)}</strong><small>${activeFeatures.some(a=>a.key===f.key)?'Current navigation':'Saved rollout setting'}</small></span><select data-feature="${f.key}" aria-label="${esc(f.label)} visibility"><option value="" ${override==null?'selected':''}>Position default</option><option value="true" ${override?.enabled===true?'selected':''}>Show</option><option value="false" ${override?.enabled===false?'selected':''}>Hide</option></select></label>`;}).join('')}</fieldset>`).join(''):'<p>No assigned accounts.</p>';};
  userSelect.onchange=draw;panel.querySelector('#feature-switches').onchange=async e=>{if(!e.target.dataset.feature)return;const key=e.target.dataset.feature,value=e.target.value,userId=userSelect.value;const message=panel.querySelector('#feature-result');e.target.disabled=true;try{await store.setFeature(userId,key,value===''?null:value==='true');await refresh();message.textContent='Visibility saved.';}catch(error){message.textContent=error.message;}finally{draw();}};
  panel.querySelector('#reset-features').onclick=async e=>{if(!userSelect.value)return;e.target.disabled=true;try{await store.setFeature(userSelect.value,'*',null);await refresh();draw();panel.querySelector('#feature-result').textContent='Position defaults restored.';}catch(error){panel.querySelector('#feature-result').textContent=error.message;}finally{e.target.disabled=false;}};draw();
 }
 function properties(){const panel=panels.properties;panel.innerHTML=`<h3>Property governance</h3><p>Assign the community manager and resident services lead for each property.</p><div class="admin-grid">${workspace.properties.map(p=>`<button class="linked" data-property="${p.id}"><strong>${esc(p.name)}</strong><span>${esc(p.location)} · ${p.active?'Active':'Archived'}</span></button>`).join('')||'<p>No properties entered yet.</p>'}</div><button class="quiet-button" data-new-property>Add property</button><div id="property-editor"></div>`;
  const edit=p=>{const editor=panel.querySelector('#property-editor');editor.innerHTML=`<form class="entry-form"><label>Property name<input name="name" required maxlength="150" value="${esc(p?.name)}"></label><label>Location<input name="location" maxlength="250" value="${esc(p?.location)}"></label><label>Units<input name="units" type="number" min="0" step="1" value="${esc(p?.units)}"></label><label>Community manager<select name="managerId">${options(roster.members.filter(m=>m.active),p?.manager_id)}</select></label><label>Resident services lead<select name="residentLeadId">${options(roster.members.filter(m=>m.active),p?.resident_lead_id)}</select></label><label class="check"><input type="checkbox" name="active" ${p?.active!==false?'checked':''}>Active property</label><button class="primary-button">Save property</button><p role="status"></p></form>`;bindSave(editor,f=>store.saveProperty({id:p?.id,name:f.get('name'),location:f.get('location'),units:f.get('units'),managerId:f.get('managerId'),residentLeadId:f.get('residentLeadId'),active:f.has('active'),expectedRevision:p?.revision??null}),properties);};
  panel.querySelector('[data-new-property]').onclick=()=>{if(guard())edit(null);};panel.querySelectorAll('[data-property]').forEach(b=>b.onclick=()=>{if(guard())edit(workspace.properties.find(p=>p.id===b.dataset.property));});
 }
 async function records(){const panel=panels.records;let page=0,rows=[],generation=0;panel.innerHTML=`<h3>Operating data</h3><button type="button" class="quiet-button" id="open-archive">Archived records</button><section id="archive-panel" hidden></section><form id="record-filter" class="admin-filter"><label class="field">Records<select name="kind"><option value="metrics">Metric updates</option><option value="weekly">Weekly submissions and drafts</option><option value="actions">Weekly action items</option></select></label><label class="field">Search<input name="search" type="search" maxlength="200"></label><button class="quiet-button">Search</button></form><div id="record-table"></div><div class="form-footer"><button class="quiet-button" id="records-back">Previous page</button><button class="quiet-button" id="records-next">Next page</button><button class="quiet-button" id="records-export">Export this page</button></div><p role="status" id="record-result"></p>`;
  panel.querySelector('#open-archive').onclick=async()=>{const archive=panel.querySelector('#archive-panel');archive.hidden=!archive.hidden;if(!archive.hidden)await mountArchive(archive,store);}; const form=panel.querySelector('#record-filter'),result=panel.querySelector('#record-result');const load=async()=>{const current=++generation;result.textContent='Loading records…';panel.querySelector('#records-export').disabled=true;try{const response=await store.adminRecords(form.elements.kind.value,page,form.elements.search.value);if(current!==generation)return;rows=response.slice(0,100);const keys=[...new Set(rows.flatMap(Object.keys))];panel.querySelector('#record-table').innerHTML=rows.length?`<div class="admin-table-wrap"><table><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${typeof r[k]==='object'&&r[k]!==null?`<details><summary>View record</summary><pre>${esc(JSON.stringify(r[k],null,2))}</pre></details>`:esc(r[k])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<p>No records match this view.</p>';result.textContent=`Page ${page+1} · ${rows.length} records`;panel.querySelector('#records-back').disabled=page===0;panel.querySelector('#records-next').disabled=response.length<=100;panel.querySelector('#records-export').disabled=!rows.length;}catch(error){result.textContent=error.message;}};
  form.onsubmit=e=>{e.preventDefault();page=0;load();};panel.querySelector('#records-back').onclick=()=>{page--;load();};panel.querySelector('#records-next').onclick=()=>{page++;load();};panel.querySelector('#records-export').onclick=()=>download(rows,`compass-${form.elements.kind.value}-page-${page+1}.csv`);await load();
 }
 async function renderPanel(){if(selected==='users'||selected==='targets')return;if(selected==='positions')return mountPositions(panels.positions,store,roster,async()=>{Object.assign(roster,await store.members());refreshPositionChoices();});if(selected==='governance')return mountMetricGovernance(panels.governance,store,roster);if(selected==='permissions')return permissions();if(selected==='records')return records();await refresh();if(selected==='teams')teams();if(selected==='features')rollout();if(selected==='properties')properties();if(selected==='history')panels.history.innerHTML=`<h3>Admin history</h3><p>Most recent 100 recorded changes.</p>${workspace.audit.map(e=>`<article class="card learn-card"><strong>${esc(e.action.replaceAll('_',' '))}</strong><p>${esc(e.actor||'System Admin')} · ${esc(new Date(e.recorded_at).toLocaleString())}</p><small>${esc(e.subject)}</small></article>`).join('')||'<p>No Admin changes recorded yet.</p>'}`;}
}
